version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env.prod
    networks:
      - local-net

  proxy:
    image: 'jwilder/nginx-proxy:alpine'
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - local-net

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - conf.d:/etc/nginx/conf.d
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    networks:
      - local-net


volumes:
  certs:
  conf.d:
  vhost.d:
  html:

networks:
    local-net:
        driver: bridge


