"""add hooks and hits

Revision ID: 49582bf94974
Revises: 0e719d85c4d8
Create Date: 2022-07-12 01:22:06.206099

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = '49582bf94974'
down_revision = '0e719d85c4d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    conn = op.get_bind()
    conn.execute(text("""CREATE EXTENSION IF NOT EXISTS "uuid-ossp";"""))
    conn.execute(text("""ALTER EXTENSION "uuid-ossp" SET SCHEMA public;"""))

    op.create_table('hooks',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('method', postgresql.ENUM('GET', 'POST', name='hookmethods'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('cron', sa.String(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_hit', sa.DateTime(), nullable=True),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hits',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('hook_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('response_status', sa.String(), nullable=True),
    sa.Column('response_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hits')
    op.drop_table('hooks')
    # ### end Alembic commands ###
