"""use ulid instead of uuids

Revision ID: e3ac4394a02e
Revises: e57a901f835a
Create Date: 2022-07-26 08:40:41.888615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ac4394a02e'
down_revision = 'e57a901f835a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("""alter table runs alter column id type varchar using id::varchar;""")
    conn.execute("""alter table hits alter column id type varchar using id::varchar;""")
    conn.execute("""alter table hooks alter column id type varchar using id::varchar;""")
    conn.execute("""alter table hits alter column hook_id type varchar using id::varchar;""")
    conn.execute("""alter table hits alter column run_id type varchar using id::varchar;""")
    conn.execute("""alter table runs alter column id set default generate_ulid();""")
    conn.execute("""alter table hooks alter column id set default generate_ulid();""")
    conn.execute("""alter table hits alter column id set default generate_ulid();""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # this migration won't work
    """alter table runs alter column id type uuid using id::uuid;"""
    """alter table hits alter column id type uuid using id::uuid;"""
    """alter table hooks alter column id type uuid using id::uuid;"""
    # ### end Alembic commands ###

