name: Deploy to Digital Ocean

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy to DO
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: ls
